### ISSUE TITLE
high latency leads to errors

### ISSUE THREAD

**Issue by npfoss** [npfoss/courseroad2#120]
see #117 for some examples I got while using my phone as a hotspot

I'm not sure if we should even do anything about this by MVP because it doesn't seem to be a problem on campus. The quick fix is probably to just not let anyone do anything until all the stuff has loaded, and the best fix is to prevent only the actions which cause problems or handle unloaded resources more elegantly (when computing semester color, for example).

**Comment by ttpcodes** [comment]
I think this has already been implemented (the quick fix, at least). Are we still looking to implement the best fix described above?

**Comment by npfoss** [comment]
I think this is fine
