### ISSUE TITLE
half-term subject prereq warnings

### ISSUE THREAD

**Issue by npfoss** [npfoss/courseroad2#138]
6.0002 has a warning because 6.0001 is a prereq, not a coreq, but of course in reality you can take them in the same semester.

Not sure what to do about this one. We definitely don't want to start dealing with the larger set of problems associated with half-term subjects. Is just making all of the prereqs of any second-half term class be treated like coreqs too heavy handed? Can we even tell which classes are second half half-term classes?

I think we should punt this to post-MVP, but probably not farther than that because this is a really common combo.

**Comment by georgiashay** [comment]
I've run into this with more than one combo and a quick print of the subjects it affects is longer than expected (~150).  (Another example would be 6.041A/6.041B which I also think is pretty common?).  Should be a quick fix so I think I'll just do it now since I'm sure we will get complaints.

**Comment by npfoss** [comment]
Thanks for taking care of this!
