### ISSUE TITLE
Placeholder classes have no hours

### ISSUE THREAD

**Issue by georgiashay** [npfoss/courseroad2#162]
This makes the total # of hours shown at the top of the semester artificially lower.

Some options
- Put in the average hours for all matching classes (would also show in the class info card though, which is not necessarily what we want)
- Put in 12 hours (may not be very accurate)
- Put in average hours but don't show in class info card (check if it's a generic course)

I think this should be addressed now since it will likely affect many people and could lead them to make poor decisions.

**Comment by npfoss** [comment]
I think we should just put 12 (really the number of units). Because that's almost always an overestimate, so it's not damaging, but it provides an incentive to actually put in the true class. We could also add a `*` to the semester hours and "hours" row of the info card

**Comment by georgiashay** [comment]
oh shoot I just implemented the average thing.  Would it be better to switch to 12 now or use the average since I already did it? (And yeah, looks like average is more like 6 or 7)

**Comment by georgiashay** [comment]
Side-note: I do think it's valuable for planning out when the best time is to take a CI-H for example, as opposed to a regular HASS

**Comment by npfoss** [comment]
Nah average is good. We should just still add disclaimers/`*`s
