### ISSUE TITLE
Spooky dragging behavior

### ISSUE THREAD

**Issue by wishdasher** [npfoss/courseroad2#179]
I somehow managed to drag the shadows of multiple elements (including the semester info).

![image](https://user-images.githubusercontent.com/9587565/56341689-d98cbc80-6183-11e9-92a2-79523e174e51.png)

**Comment by npfoss** [comment]
On this topic, I've also dragged things, had the semester turn green, and dropped them (all very quickly) and it not get added to the semester

**Comment by npfoss** [comment]
Also I just had that exact same spooky drag happen on Google Calendar so I think it's not an us problem
