### ISSUE TITLE
Percentages no longer show on hover in audit

### ISSUE THREAD

**Issue by georgiashay** [npfoss/courseroad2#94]
Percentages only show on hover in the audit when you are on base requirements (a single class or plain-string type requirement).  This appears to be due to this commit https://github.com/npfoss/courseroad2/pull/69/commits/a9fef5d3bef6c3c606be351b4f7d0a029ac75315 where icons were removed for everything but these base requirements.  The icon was activating the the tooltip, so it can no longer do that.

Personally I think an icon is helpful anyway for an immediate visual indication of if a requirement is completed (rather than trying to read the progress bar, which might go off screen, or hover to see percentage). 

Either way, we need to replace the icons, or activate the tooltip using something else.

**Comment by npfoss** [comment]
part of #141
